before_script:
  - apt-get update
  - apt-get install -y python3-requests p7zip-full wget
  - apt-get install -y build-essential libgl1-mesa-dev libglib2.0-dev
  - wget https://git.kaidan.im/lnj/qli-installer/raw/master/qli-installer.py
  - chmod +x qli-installer.py
  - ./qli-installer.py 5.12.0 linux desktop
  - PATH=$PATH:./5.12.0/gcc_64/bin

stages:
  - build

# lint:
#   stage: lint
#   script:
#     - qmllint desktop/qml/*.qml

build:
  stage: build
  script:
    - find qmake
    - sh dist/build_linux.sh
