before_script:
  - apt-get update -yq && apt-get install -y qtcreator qmlscene qt5-qmltooling-plugins qtbase5-dev-tools qtcreator-doc qtdeclarative5-dev-tools qttools5-dev-tools qttranslations5-l10n qtxmlpatterns5-dev-tools qt5-default g++

stages:
  - lint
  - build

lint:
  stage: lint
  script:
    - qmllint desktop/qml/*.qml

build:
  stage: build
  script:
    - qmake qrop.pro
    - make
