before_script:
  - apt-get update
  - apt-get install -y python3-requests p7zip-full wget
  - wget https://git.kaidan.im/lnj/qli-installer/raw/master/qli-installer.py
  - chmod +x qli-installer.py
  - ./qli-installer.py 5.12.0 linux desktop

stages:
  - lint
  - build

lint:
  stage: lint
  script:
    - qmllint desktop/qml/*.qml

build:
  stage: build
  script:
    - sh dist/build_linux.sh
