 before_script:
   - apt-get update -yq && apt-get install -y qtchooser pkg-config qt5base-dev qtdeclarative5-dev qt5-qmake qt5-default qttools5-dev-tools

stages:
  - lint
  - build

lint:
  stage: lint
  script:
    - qmllint desktop/qml/*.qml

build:
  stage: build
  script:
    - qmake qrop.pro
    - make
