image: andreh11/qt:5.12.5-trusty

normal-build:
  script:
    - bash dist/linux/build.sh
  except:
    - tags

release-build:
  script:
    - bash dist/linux/build.sh
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - Qrop*.AppImage
    expire_in: 1 weeks
  only:
   - tags
