stages:
  - build
  - deploy

normal-build:linux:
  stage: build
  image: andreh11/qt:5.12.5-trusty
  script:
    - bash dist/linux/build.sh
  except:
    - master
    - tags

normal-build:windows32:
  stage: build
  image: andreh11/qt-mxe:5.15-shared
  variables:
    WINDOWS_ARCH: "32bit"
  script:
    - bash dist/windows-mxe/build.sh
  except:
    - master
    - tags

normal-build:windows64:
  stage: build
  image: andreh11/qt-mxe:5.15-shared
  variables:
    WINDOWS_ARCH: "64bit"
  script:
    - bash dist/windows-mxe/build.sh
  except:
    - master
    - tags

master-build:linux:
  stage: build
  image: andreh11/qt:5.12.5-trusty
  variables:
    QROP_BUILD_TYPE: "snapshot"
  script:
    - bash dist/linux/build.sh
    - bash dist/linux/deploy.sh
  only:
    - master
  except:
    - tags

master-build:windows32:
  stage: build
  image: andreh11/qt-mxe:5.15-shared
  variables:
    QROP_BUILD_TYPE: "snapshot"
    WINDOWS_ARCH: "32bit"
  script:
    - bash dist/windows-mxe/build.sh
    - bash dist/windows-mxe/deploy.sh
  only:
    - master
  except:
    - tags

master-build:windows64:
  stage: build
  image: andreh11/qt-mxe:5.15-shared
  script:
  variables:
    QROP_BUILD_TYPE: "snapshot"
    WINDOWS_ARCH: "64bit"
  script:
    - bash dist/windows-mxe/build.sh
    - bash dist/windows-mxe/deploy.sh
  only:
    - master
  except:
    - tags

release-build:linux:
  stage: build
  image: andreh11/qt:5.12.5-trusty
  variables:
    QROP_BUILD_TYPE: "release"
  script:
    - bash dist/linux/build.sh
    - bash dist/linux/deploy.sh
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - Qrop*.AppImage
    expire_in: 1 weeks
  only:
   - tags

release-build:windows32:
  stage: build
  image: andreh11/qt-mxe:5.15-shared
  variables:
    QROP_BUILD_TYPE: "release"
    WINDOWS_ARCH: "32bit"
  script:
    - bash dist/windows-mxe/build.sh
    - bash dist/windows-mxe/deploy.sh
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - Qrop*.exe
    expire_in: 1 weeks
  only:
   - tags

release-build:windows64:
  stage: build
  image: andreh11/qt-mxe:5.15-shared
  variables:
    QROP_BUILD_TYPE: "release"
    WINDOWS_ARCH: "64bit"
  script:
    - bash dist/windows-mxe/build.sh
    - bash dist/windows-mxe/deploy.sh
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - Qrop*.exe
    expire_in: 1 weeks
  only:
   - tags

release-deploy:linux:
  stage: deploy
  image: andreh11/qt:5.12.5-trusty
  variables:
    QROP_BUILD_TYPE: "release"
  script:
    - bash dist/gitlab-release.sh
  only:
    - tags
