before_script:
  - apt-get update
  - apt-get install -y libdbus-1-3 libfreetype6 libfontconfig1 wget tree p7zip-full python3-requests
  - apt-get install -y build-essential libgl1-mesa-dev libglib2.0-dev mesa-common-dev libglu1-mesa-dev
  - wget https://git.kaidan.im/lnj/qli-installer/raw/master/qli-installer.py
  - chmod +x qli-installer.py
  - ./qli-installer.py 5.12.0 linux desktop
  - export PATH=$PWD/5.12.0/gcc_64/bin
  - export QMAKESPEC=$PWD/5.12.0/gcc_64/mkspecs/linux-g++

stages:
  - lint
  - build

lint:
  stage: lint
  script:
    - qmllint desktop/qml/*.qml

build:
  stage: build
  script:
    - mkdir build;
    - cd build;
    - qmake -spec $QMAKESPEC -config release ..;
    - make -j 4;
    - mkdir -p deploy/usr/bin deploy/usr/lib deploy/usr/share;
    - mkdir deploy/usr/share/applications;
    - find . \( -name "moc_*" -or -name "*.o" -or -name "qrc_*" -or -name "Makefile*" -or -name "*.a" \) -exec rm {} \;
    - cp -R core/* desktop/* deploy/usr/bin
    - cd deploy;
    - cp ../../logo.png desktop.png
    - cp ../../dist/Qrop.desktop usr/share/applications
    - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/5/linuxdeployqt-5-x86_64.AppImage"
    - chmod a+x linuxdeployqt*.AppImage;
    - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH;
    - ./linuxdeployqt*.AppImage usr/share/applications/Qrop.desktop -verbose=2 -qmldir=/home/ah/src/qrop/desktop/qml -bundle-non-qt-libs -extra-plugins=sqldrivers,imageformats/libqsvg.so
    - ./linuxdeployqt*.AppImage usr/share/applications/Qrop.desktop -verbose=2 -qmldir=/home/ah/src/qrop/desktop/qml -appimage
    - find . | grep AppImage;

  artifacts:
    paths:
      - build/deploy/Qrop*.AppImage
