version: 0.1_b{build}

environment:
  matrix:
    # MSVC x86
    - name: win32
      platform: amd64_x86
      qt: 5.11\msvc2015
      suffix: msvc2015

    # MSVC x64
    - name: win64
      platform: amd64
      qt: 5.11\msvc2015_64
      suffix: msvc2015

init:
  - set PATH=C:\Qt\%qt%\bin;%PATH%
  - if not %platform%==mingw call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %platform%

build_script:
  - cd C:\projects\qrop
  - qmake -v
    && qmake qrop.pro CONFIG+=release
    && mingw32-make
