version: 0.1_b{build}
configuration: Release

branches:
  only:
    - master

environment:
  DEPLOY_DIR: Qrop-%APPVEYOR_BUILD_VERSION%
  matrix:
    # MSVC x86
    - name: win32
      job: win32
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      platform: amd64_x86
      qt: 5.11\msvc2015
      suffix: msvc2015
      arch: x86

    # MSVC x64
    - name: amd64
      job: amd64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      platform: amd64
      qt: 5.11\msvc2017_64
      suffix: msvc2017
      arch: x64

init:
  - set PATH=C:\Qt\%qt%\bin;%PATH%
  - if %arch%==x86 call "%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %arch%
  - if %arch%==x68 call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - cd /D "%APPVEYOR_BUILD_FOLDER%"

build_script:
  - cd C:\projects\qrop
  - qmake -config release qrop.pro PREFIX="%DEPLOY_DIR%"
  - nmake.exe

after_build:
  - nmake install
  - cmd: find . \( -name "moc_*" -or -name "*.o" -or -name "qrc_*" -or -name "Makefile*" -or -name "*.a" \) -exec rm {} \;
  - cmd: cp core/release/*.dll "desktop/%DEPLOY_DIR%""
  - cd desktop;
  - windeployqt --release --qmldir qml "%DEPLOY_DIR%\desktop.exe"
  - 7z a qrop-%name%.zip "%DEPLOY_DIR%"
  - cd ..

artifacts:
  - path: desktop/qrop-%name%-%version%.zip
    name: portable
