version: 0.1_b{build}
configuration: Release

branches:
  only:
    - master

environment:
  DEPLOY_DIR: Qrop-%APPVEYOR_BUILD_VERSION%
  matrix:
    # MSVC x86
    - name: win32
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      platform: amd64_x86
      qt: 5.11\msvc2015
      suffix: msvc2017
      arch: x86

    # MSVC x64
    - name: win64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      platform: amd64
      qt: 5.11\msvc2017_64
      suffix: msvc2017
      arch: x64

init:
  - set PATH=C:\Qt\%qt%\bin;%PATH%
  - call "%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %arch%
  - cd /D "%APPVEYOR_BUILD_FOLDER%"

build_script:
  - cd C:\projects\qrop
  - qmake -config release qrop.pro PREFIX="%DEPLOY_DIR%"
  - nmake.exe

after_build:
  - nmake install
  - windeployqt --release --qmldir desktop/qml "desktop\%DEPLOY_DIR%\desktop.exe"  
  - 7z a "qrop%version%-%name.zip" "desktop\%DEPLOY_DIR%" 

artifacts:
  - path: "qrop-%version%-%name.zip" 
    name: portable
